// A hand-written, source-driven compiler pipeline. The grammar and every downstream
// artifact are derived from the token stream and AST (never from canned output).
const keywords = new Set(['int','float','if','else','while','print']);
export class CompileError extends Error { constructor(message, token, kind='Syntax') { super(message); this.kind=kind; this.line=token?.line??1; this.column=token?.column??1; } }
export function lex(source) {
  const out=[], errors=[]; let i=0,line=1,column=1;
  const advance=()=>{const c=source[i++]; if(c==='\n'){line++;column=1}else column++; return c};
  while(i<source.length){const c=source[i]; if(/\s/.test(c)){advance();continue}
    if(c==='/'&&source[i+1]==='/'){while(i<source.length&&advance()!=='\n'){} continue}
    if(c==='/'&&source[i+1]==='*'){const start={line,column};advance();advance();let closed=false;while(i<source.length){if(source[i]==='*'&&source[i+1]==='/'){advance();advance();closed=true;break}advance()}if(!closed)errors.push(new CompileError('Unterminated block comment',start,'Lexical'));continue}
    const start={line,column}, rest=source.slice(i); let m;
    if((m=/^(?:\d+\.\d+|\d+)(?:[eE][+-]?\d+)?/.exec(rest))){for(let n=0;n<m[0].length;n++)advance();out.push({...start,type:/[.eE]/.test(m[0])?'FLOAT':'INT',value:m[0]});continue}
    if((m=/^[A-Za-z_][A-Za-z0-9_]*/.exec(rest))){for(let n=0;n<m[0].length;n++)advance();out.push({...start,type:keywords.has(m[0])?m[0].toUpperCase():'ID',value:m[0]});continue}
    const op=['==','!=','<=','>=','&&','||'].find(x=>rest.startsWith(x)); if(op){advance();advance();out.push({...start,type:op,value:op});continue}
    if('+-*/%<>=!;:,(){}'.includes(c)){advance();out.push({...start,type:c,value:c});continue}
    advance(); errors.push(new CompileError(`Invalid character '${c}'`,start,'Lexical'));
  }
  out.push({type:'EOF',value:'EOF',line,column}); return {tokens:out,errors};
}
export const grammar=`Program → Statement* EOF\nStatement → Declaration | Assignment ';' | Print ';' | If | While | Block\nDeclaration → ('int'|'float') ID ('=' Expression)? ';'\nIf → 'if' '(' Condition ')' Statement ('else' Statement)?\nWhile → 'while' '(' Condition ')' Statement\nBlock → '{' Statement* '}'\nCondition → Expression (RelOp Expression)?\nExpression → Term (('+'|'-') Term)*\nTerm → Unary (('*'|'/'|'%') Unary)*\nUnary → ('-'|'!') Unary | Primary\nPrimary → INT | FLOAT | ID | '(' Expression ')'`;
export function parse(tokens){let p=0;const errors=[];const peek=()=>tokens[p]??tokens.at(-1),take=()=>tokens[p++]??tokens.at(-1),is=(...types)=>types.includes(peek().type);function expect(type,msg){if(is(type))return take();throw new CompileError(msg,peek())}
  function primary(){if(is('INT','FLOAT')){const t=take();return {kind:'Literal',value:Number(t.value),raw:t.value,type:t.type==='INT'?'int':'float',loc:t}}if(is('ID')){const t=take();return {kind:'Identifier',name:t.value,loc:t}}if(is('(')){take();const e=expression();expect(')',"Expected ')' after expression.");return e}throw new CompileError('Expected a number, identifier, or parenthesized expression.',peek())}
  function unary(){if(is('-','!')){const t=take();return {kind:'Unary',op:t.type,arg:unary(),loc:t}}return primary()}
  function binary(next,ops){let n=next();while(is(...ops)){const t=take();n={kind:'Binary',op:t.type,left:n,right:next(),loc:t}}return n}
  function term(){return binary(unary,['*','/','%'])} function expression(){return binary(term,['+','-'])}
  function condition(){const a=expression();if(is('<','>','<=','>=','==','!=')){const t=take();return {kind:'Binary',op:t.type,left:a,right:expression(),loc:t}}return a}
  function statement(){const start=peek();try{
    if(is('INT','FLOAT')){const t=take(),id=expect('ID','Expected an identifier after type.');let init=null;if(is('=')){take();init=expression()}expect(';',`Expected ';' after declaration.`);return {kind:'Declaration',type:t.value,name:id.value,init,loc:t}}
    if(is('ID')){const id=take();expect('=',"Expected '=' in assignment.");const value=expression();expect(';',"Expected ';' after assignment.");return {kind:'Assignment',name:id.value,value,loc:id}}
    if(is('PRINT')){const t=take();expect('(',"Expected '(' after print.");const value=expression();expect(')',"Expected ')' after print expression.");expect(';',"Expected ';' after print.");return {kind:'Print',value,loc:t}}
    if(is('IF')){const t=take();expect('(',"Expected '(' after if.");const test=condition();expect(')',"Expected ')' after condition.");const yes=statement();let no=null;if(is('ELSE')){take();no=statement()}return {kind:'If',test,yes,no,loc:t}}
    if(is('WHILE')){const t=take();expect('(',"Expected '(' after while.");const test=condition();expect(')',"Expected ')' after condition.");return {kind:'While',test,body:statement(),loc:t}}
    if(is('{')){const t=take(),body=[];while(!is('}','EOF')){const before=p;body.push(statement());if(p===before)take()}expect('}',"Expected '}' to close block.");return {kind:'Block',body,loc:t}}
    throw new CompileError('Expected a declaration, assignment, print, if, while, or block.',peek());
  }catch(e){errors.push(e);while(!is(';','}','EOF'))take();if(is(';'))take();return {kind:'Error',loc:start,message:e.message}}}
  const body=[];while(!is('EOF')){const before=p;body.push(statement());if(p===before)take()}return {ast:{kind:'Program',body},errors};
}
export function analyze(ast){const symbols=[],byName=new Map(),errors=[];let addr=0;function expr(n){if(!n)return 'void';if(n.kind==='Literal')return n.type;if(n.kind==='Identifier'){const s=byName.get(n.name);if(!s)errors.push(new CompileError(`Variable '${n.name}' is not declared.`,n.loc,'Semantic'));return s?.type??'int'}if(n.kind==='Unary')return expr(n.arg);if(n.kind==='Binary'){const a=expr(n.left),b=expr(n.right);if(a!==b&&a!=='int'&&b!=='int')errors.push(new CompileError(`Incompatible operands '${a}' and '${b}'.`,n.loc,'Semantic'));return ['<','>','<=','>=','==','!='].includes(n.op)?'int':(a==='float'||b==='float'?'float':'int')}return 'int'}
  function stmt(s){if(!s||s.kind==='Error')return;if(s.kind==='Block'){s.body.forEach(stmt);return}if(s.kind==='Declaration'){if(byName.has(s.name))errors.push(new CompileError(`Duplicate declaration of '${s.name}'.`,s.loc,'Semantic'));else{const sym={identifier:s.name,type:s.type,address:addr++,scope:'global',line:s.loc.line};symbols.push(sym);byName.set(s.name,sym)}const t=expr(s.init);if(s.init&&t!==s.type&&t!=='int')errors.push(new CompileError(`Cannot initialize ${s.type} with ${t}.`,s.loc,'Semantic'));return}if(s.kind==='Assignment'){const sym=byName.get(s.name);if(!sym)errors.push(new CompileError(`Variable '${s.name}' is not declared.`,s.loc,'Semantic'));const t=expr(s.value);if(sym&&sym.type!==t&&t!=='int')errors.push(new CompileError(`Cannot assign ${t} to ${sym.type} '${s.name}'.`,s.loc,'Semantic'));return}if(s.kind==='Print'){expr(s.value);return}if(s.kind==='If'){expr(s.test);stmt(s.yes);stmt(s.no);return}if(s.kind==='While'){expr(s.test);stmt(s.body)}}ast.body.forEach(stmt);return {symbols,errors};}
export function generateTac(ast){const code=[];let temp=0,label=0;const t=()=>`t${++temp}`,l=()=>`L${++label}`;function e(n){if(n.kind==='Literal')return String(n.value);if(n.kind==='Identifier')return n.name;if(n.kind==='Unary'){const a=e(n.arg);const x=t();code.push(`${x} = ${n.op}${a}`);return x}const a=e(n.left),b=e(n.right),x=t();code.push(`${x} = ${a} ${n.op} ${b}`);return x}function cond(n,yes,no){if(n.kind==='Binary'&&['<','>','<=','>=','==','!='].includes(n.op)){const a=e(n.left),b=e(n.right);code.push(`if ${a} ${n.op} ${b} goto ${yes}`)}else{const v=e(n);code.push(`if ${v} != 0 goto ${yes}`)}code.push(`goto ${no}`)}function s(n){if(!n||n.kind==='Error')return;if(n.kind==='Program'||n.kind==='Block'){n.body.forEach(s);return}if(n.kind==='Declaration'){if(n.init)code.push(`${n.name} = ${e(n.init)}`);return}if(n.kind==='Assignment'){code.push(`${n.name} = ${e(n.value)}`);return}if(n.kind==='Print'){code.push(`print ${e(n.value)}`);return}if(n.kind==='If'){const a=l(),b=l(),end=l();cond(n.test,a,n.no?b:end);code.push(`${a}:`);s(n.yes);if(n.no){code.push(`goto ${end}`,`${b}:`);s(n.no)}code.push(`${end}:`);return}if(n.kind==='While'){const head=l(),body=l(),end=l();code.push(`${head}:`);cond(n.test,body,end);code.push(`${body}:`);s(n.body);code.push(`goto ${head}`,`${end}:`)}}s(ast);return code}
export function optimize(code){let constants=new Map(),out=[];for(let line of code){if(/^L\d+:$/.test(line)||/^(if |goto )/.test(line))constants.clear();for(const [name,value] of constants)line=line.replace(new RegExp(`\\b${name}\\b`,'g'),value);let m=line.match(/^(t\d+) = (-?\d+(?:\.\d+)?) ([+\-*/%]) (-?\d+(?:\.\d+)?)$/);if(m){const a=Number(m[2]),b=Number(m[4]);let v=m[3]==='+'?a+b:m[3]==='-'?a-b:m[3]==='*'?a*b:m[3]==='/'?a/b:a%b;if(Number.isFinite(v)){constants.set(m[1],String(v));continue}}m=line.match(/^(t\d+) = (-?\d+(?:\.\d+)?)$/);if(m){constants.set(m[1],m[2]);out.push(line);continue}const def=line.match(/^(t\d+) =/);if(def)constants.delete(def[1]);out.push(line)}return out}
export function allocate(code,k=4){const vars=new Set(),live=new Map(),edges=new Map();for(const line of code){const lhs=line.match(/^(\w+) =/);const ids=line.match(/\b(?:t\d+|[A-Za-z_]\w*)\b/g)||[];for(const v of [...ids,...(lhs?[lhs[1]]:[])])if(!/^L\d+$/.test(v)&&!['if','goto','print'].includes(v))vars.add(v)}const lines=code.map((text,i)=>({text,i,def:(text.match(/^(\w+) =/)||[])[1],use:(text.match(/(?:=|if|print)\s+(.+)/)||[])[1]?.match(/\b(?:t\d+|[A-Za-z_]\w*)\b/g)||[]}));let current=new Set();for(let i=lines.length-1;i>=0;i--){const {def,use}=lines[i];if(def){live.set(def,[...(live.get(def)||[]),i]);edges.set(def,edges.get(def)||new Set());for(const x of current)if(x!==def){edges.get(def).add(x);(edges.get(x)||edges.set(x,new Set()).get(x)).add(def)}current.delete(def)}use.forEach(x=>{if(vars.has(x)){current.add(x);live.set(x,[...(live.get(x)||[]),i]);edges.set(x,edges.get(x)||new Set())}})}const colors={};for(const v of [...vars].sort((a,b)=>(edges.get(b)?.size||0)-(edges.get(a)?.size||0))){const used=new Set([...(edges.get(v)||[])].map(x=>colors[x]).filter(Boolean));let c=1;while(used.has(`R${c}`))c++;colors[v]=c<=k?`R${c}`:`spill[${v}]`}return {variables:[...vars],edges:Object.fromEntries([...edges].map(([a,b])=>[a,[...b]])),colors,registerCount:k,liveRanges:Object.fromEntries(live)}}
export function assembly(code,allocation){return code.map(line=>{let m=line.match(/^(\w+) = (\w+) ([+\-*/%]) (\w+)$/);if(m)return `LOAD ${allocation.colors[m[2]]||'MEM'}, ${m[2]}\n${({'+':'ADD','-':'SUB','*':'MUL','/':'DIV','%':'REM'})[m[3]]} ${allocation.colors[m[4]]||'MEM'}\nSTORE ${m[1]}, ${allocation.colors[m[2]]||'MEM'}`;m=line.match(/^(\w+) = (.+)$/);if(m)return `LOAD ${allocation.colors[m[2]]||'MEM'}, ${m[2]}\nSTORE ${m[1]}, ${allocation.colors[m[2]]||'MEM'}`;return line}).join('\n')}
export function emitWat(ast){const names=new Set(),out=[];function gatherExpr(n){if(!n)return;if(n.kind==='Identifier')names.add(n.name);if(n.kind==='Binary'){gatherExpr(n.left);gatherExpr(n.right)}if(n.kind==='Unary')gatherExpr(n.arg)}function gather(s){if(!s)return;if(s.kind==='Declaration'||s.kind==='Assignment')names.add(s.name);if(s.kind==='Declaration')gatherExpr(s.init);if(s.kind==='Assignment'||s.kind==='Print')gatherExpr(s.value);if(s.kind==='If'){gatherExpr(s.test);gather(s.yes);gather(s.no)}if(s.kind==='While'){gatherExpr(s.test);gather(s.body)}if(s.kind==='Block'||s.kind==='Program')s.body.forEach(gather)}gather(ast);const ids=[...names],idx=Object.fromEntries(ids.map((n,i)=>[n,i]));function e(n){if(n.kind==='Literal')return `(f64.const ${n.value})`;if(n.kind==='Identifier')return `(global.get $${n})`;if(n.kind==='Unary')return n.op==='-'?`(f64.neg ${e(n.arg)})`:`(f64.eq ${e(n.arg)} (f64.const 0))`;const op={'+' :'add','-':'sub','*':'mul','/':'div','%':'rem_s','<':'lt','>':'gt','<=':'le','>=':'ge','==':'eq','!=':'ne'}[n.op];const type=['<','>','<=','>=','==','!='].includes(n.op)?'f64':'f64';return `(${type}.${op} ${e(n.left)} ${e(n.right)})`}function s(n){if(!n)return;if(n.kind==='Program'||n.kind==='Block'){n.body.forEach(s);return}if(n.kind==='Declaration'){if(n.init)out.push(`(global.set $${n.name} ${e(n.init)})`);return}if(n.kind==='Assignment'){out.push(`(global.set $${n.name} ${e(n.value)})`);return}if(n.kind==='Print'){out.push(`(call $print ${e(n.value)})`);return}if(n.kind==='If'){out.push(`(if ${e(n.test)} (then ${body(n.yes)})${n.no?` (else ${body(n.no)})`:''})`);return}if(n.kind==='While'){out.push(`(block (loop ${body(n.body)} (br_if 0 (i32.eqz ${e(n.test)})) (br 0)))`)}}function body(n){const before=out.length;s(n);return out.splice(before).join(' ')}s(ast);const globals=ids.map(n=>`(global $${n} (mut f64) (f64.const 0))`).join('\n  ');const wat=`(module\n  (import "env" "print" (func $print (param f64)))\n  ${globals}\n  (func (export "run") ${out.join('\n    ')})\n)`;return {wat,names:ids}}
export async function runWat(wat){const wabt=await import('wabt');const api=await (wabt.default||wabt)();const mod=api.parseWat('program.wat',wat);const {buffer}=mod.toBinary({});const printed=[];const instance=await WebAssembly.instantiate(buffer,{env:{print:x=>printed.push(Number(x))}});instance.instance.exports.run();return printed}
export function emitWatSource(ast){const names=new Set(),instructions=[];function scanExpr(n){if(!n)return;if(n.kind==='Identifier')names.add(n.name);if(n.kind==='Binary'){scanExpr(n.left);scanExpr(n.right)}if(n.kind==='Unary')scanExpr(n.arg)}function scan(s){if(!s)return;if(s.kind==='Program'||s.kind==='Block')s.body.forEach(scan);if(s.kind==='Declaration'||s.kind==='Assignment'){names.add(s.name);scanExpr(s.value||s.init)}if(s.kind==='Print')scanExpr(s.value);if(s.kind==='If'){scanExpr(s.test);scan(s.yes);scan(s.no)}if(s.kind==='While'){scanExpr(s.test);scan(s.body)}}scan(ast);function expr(n){if(n.kind==='Literal')return `(f64.const ${n.value})`;if(n.kind==='Identifier')return `(global.get $${n.name})`;if(n.kind==='Unary')return n.op==='-'?`(f64.neg ${expr(n.arg)})`:`(f64.eq ${expr(n.arg)} (f64.const 0))`;if(n.op==='%')return `(f64.convert_i64_s (i64.rem_s (i64.trunc_f64_s ${expr(n.left)}) (i64.trunc_f64_s ${expr(n.right)})))`;const ops={'+':'f64.add','-':'f64.sub','*':'f64.mul','/':'f64.div','%':'f64.add','<':'f64.lt','>':'f64.gt','<=':'f64.le','>=':'f64.ge','==':'f64.eq','!=':'f64.ne'};return `(${ops[n.op]} ${expr(n.left)} ${expr(n.right)})`}function test(n){return n.kind==='Binary'&&['<','>','<=','>=','==','!='].includes(n.op)?expr(n):`(f64.ne ${expr(n)} (f64.const 0))`}function emit(s){if(!s)return;if(s.kind==='Program'||s.kind==='Block'){s.body.forEach(emit);return}if(s.kind==='Declaration'){if(s.init)instructions.push(`(global.set $${s.name} ${expr(s.init)})`);return}if(s.kind==='Assignment'){instructions.push(`(global.set $${s.name} ${expr(s.value)})`);return}if(s.kind==='Print'){instructions.push(`(call $print ${expr(s.value)})`);return}if(s.kind==='If'){instructions.push(`(if ${test(s.test)} (then ${emitNested(s.yes)})${s.no?` (else ${emitNested(s.no)})`:''})`);return}if(s.kind==='While'){instructions.push(`(block (loop (br_if 1 (i32.eqz ${test(s.test)})) ${emitNested(s.body)} (br 0)))`)}}function emitNested(s){const n=instructions.length;emit(s);return instructions.splice(n).join(' ')}emit(ast);const globals=[...names].map(n=>`(global $${n} (mut f64) (f64.const 0))`).join('\n  ');return {names:[...names],wat:`(module\n  (import "env" "print" (func $print (param f64)))\n  ${globals}\n  (func (export "run")\n    ${instructions.join('\n    ')}\n  )\n)`}}
export function compile(source){const {tokens,errors:lexErrors}=lex(source);const {ast,errors:syntaxErrors}=parse(tokens);const semantic=analyze(ast);const valid=!lexErrors.length&&!syntaxErrors.length&&!semantic.errors.length;const tac=valid?generateTac(ast):[];const optimized=valid?optimize(tac):[];const allocation=valid?allocate(optimized):{variables:[],edges:{},colors:{},registerCount:4,liveRanges:{}};const target=valid?emitWatSource(ast):{wat:'',names:[]};return {tokens:tokens.filter(t=>t.type!=='EOF'),ast,symbols:semantic.symbols,errors:[...lexErrors,...syntaxErrors,...semantic.errors],tac,optimized,allocation,assembly:valid?assembly(optimized,allocation):'',...target,valid}}
